# Generated by Django 3.0.8 on 2023-04-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=300)),
                ('following_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=1000)),
                ('followers', models.ManyToManyField(blank=True, null=True, related_name='_profilemodel_followers_+', to='api.ProfileModel')),
                ('following', models.ManyToManyField(blank=True, null=True, related_name='_profilemodel_following_+', to='api.ProfileModel')),
            ],
        ),
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('picture', models.ImageField(upload_to='')),
                ('body', models.CharField(max_length=1000)),
                ('caption', models.CharField(max_length=200)),
                ('likes', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProfileModel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PostsModel')),
            ],
        ),
    ]
