# Generated by Django 3.0.8 on 2023-04-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='body',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
