# Generated by Django 3.0.8 on 2023-04-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commentsmodel_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='date_time_created',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
