# Generated by Django 3.0.8 on 2023-04-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230401_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='followers_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='following_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
