# Generated by Django 3.0.8 on 2023-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230401_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_profilemodel_followers_+', to='api.ProfileModel'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_profilemodel_following_+', to='api.ProfileModel'),
        ),
    ]
