# Generated by Django 3.0.8 on 2023-04-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230401_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='following_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
