# Generated by Django 3.0.8 on 2023-04-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230401_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='following_count',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='user_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
