# Generated by Django 3.0.8 on 2023-04-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230401_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profilemodel_followers_+', to='api.ProfileModel'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profilemodel_following_+', to='api.ProfileModel'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
